# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nichlas WÃ¦rnes Andersen
email: nichlas@itsnwa.com
description: Art Director & Graphic Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: nichlaswa
github_username:  itsnwa

# Build settings
markdown: kramdown
